# -*- coding: utf-8 -*-
"""biblioteca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VArhZmY2fL5hnZf4NMs0-tdH1zIm_8cy
"""

class Libro:
    def __init__(self, titulo, autor, disponible=True):
        self.titulo = titulo
        self.autor = autor
        self.disponible = disponible

    def imprimirDetalles(self):
        estado = "Disponible" if self.disponible else "Prestado"
        print(f"Título: {self.titulo}\nAutor: {self.autor}\nEstado: {estado}")

    def prestar(self):
        if self.disponible:
            self.disponible = False
            print(f"El libro '{self.titulo}' ha sido prestado.")
        else:
            print(f"El libro '{self.titulo}' no está disponible.")

    def devolver(self):
        if not self.disponible:
            self.disponible = True
            print(f"El libro '{self.titulo}' ha sido devuelto.")
        else:
            print(f"El libro '{self.titulo}' ya estaba disponible.")

print("*** 1. Creamos objetos de la clase Libro")

libro1 = Libro("Cien años de soledad", "Gabriel García Márquez")
libro2 = Libro("Don Quijote de la Mancha", "Miguel de Cervantes", disponible=False)

print(libro1.titulo)
print(libro1.autor)

print("\n\n*** 2. Imprimimos atributos con el método")
libro1.imprimirDetalles()
libro2.imprimirDetalles()

print("\n\n*** 3. Probamos métodos de préstamo y devolución")
libro1.prestar()
libro1.imprimirDetalles()

libro2.devolver()
libro2.imprimirDetalles()