# -*- coding: utf-8 -*-
"""ejercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-dORt1Zl4inQCfYY6UEOvpbiG72vJmjF
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Cuenta.py
# class Cuenta:
#     def __init__(self, cantidad, tipo, titular):
#         self.cantidad = cantidad
#         self.tipo = tipo
#         self.titular = titular
# 
#     def imprimirDetalles(self):
#         print(f"Titular: {self.titular}")
#         print(f"Tipo de cuenta: {'Débito' if self.tipo == 'D' else 'Crédito'}")
#         print(f"Saldo: {self.cantidad}")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Pruebas.py
# from Cuenta import Cuenta
# 
# print("=== Pruebas con objetos de la clase Cuenta ===")
# 
# cuenta1 = Cuenta(300, 'D', "Maria Hernandez")
# print("\nDetalles de cuenta1:")
# cuenta1.imprimirDetalles()
# 
# cuenta2 = Cuenta(1500, 'C', "Juan Pérez")
# print("\nDetalles de cuenta2:")
# cuenta2.imprimirDetalles()
#

!python Pruebas.py